# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: RC Tiling
email: your-email@domain.com
author: Your Name
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2021 RC Tiling. All Rights Reserved.'
credits: 'Central Coast Tiling Services'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Contact Us (https://tripetto.app/run/17KE6GE75J)
  - title: facebook
    url: https://www.facebook.com/rctiling
  - title: instagram
    url: https://www.instagram.com/rctiling
